New ros example
klepsydra-technologies/kpsr-tutorial pull request #25
Opened 2022-05-02 05:06 UTC by adipokala

Please, review the example and let me know if my understanding is correct.

Will squash / rebase and merge.

2022-05-05 12:57 UTC, mharshe requested changes

2022-05-16 16:26 UTC, mharshe reviewed
What the examples in the tutorials are trying to show is that you could develop your application with pub/sub architecture that only use Klepsydra Publisher* and Subscriber* and the depending on the application add ROS support for transmitting messages without changing your application. Only the part where we set up and connect the elements will have ros specific elements.

However, many real world applications make heavy use ROS message types and for these applications we want to avoid the overhead of converting data types. The purpose of these examples is to show that in fact with Klepsydra you can do that --- you can have a loose link with ROS where we have automatic conversion from standard data types to ROS messages, or you can have a deeper dependency to ROS and use the ros message types without having to deal with overhead of conversion.

So update the tutorial text to reflect this and change the rosToKpsr amd kpsrToRos functions too.

2022-05-16 16:26 UTC, mharshe commented on tutorials/chapter2.md
> +This example shows us that with Klepsydra core you can use ROS messages to exchange data between the nodes.
Add more explanation about what is the difference between this example and the others.

2022-05-16 16:26 UTC, mharshe commented on tutorials/chapter2.md
> +    // auto strpublisher = eventloop.getPublisher<std_msgs::String>("example5", 0, nullptr, nullptr);
in fact, the idea is to use kpsrPublisher to publish data. This way, any class in the rest of your code that uses Publisher* can still work and will in fact use the underlying ros publisher to actually transmit data.

For example, the SimplePublisher class in these tutorial examples has a Publisher pointer. So you could use the SimplePublisher class with these ros hooks and now without changing your original class you have added ROS support. the only thing that changes is your calls in the main() and your original SimplePublisher is agnostic to ros.

2022-05-24 05:34 UTC, pablogh-2000 reviewed
@adipokala please respond to all comments with either:
- Done (if you did code changes in response to the comment)
- Explanation (if you did no code changes in response to the comment for some reason)

2023-01-09 12:31 UTC, pablogh-2000 approved these changes

2023-01-10 17:14 UTC, merged